name: lint

on:
  pull_request:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest

  steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Prettify code
      uses: creyD/prettier_action@v3.3
      with:
        prettier_options: -w **/*.json
        only_changed: True
        dry: True
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
